branches:
  only:
    - master
sudo: required
dist: trusty
before_install:
  - sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update -y
install:
  - sudo apt-get install dotnet -y
script:
  - dotnet restore
  - dotnet pack
